INSERT INTO guild.games(id, name, "number") VALUES (1,'1969',1);
INSERT INTO guild.games(id, name, "number") VALUES (2,'7rosso',1);
INSERT INTO guild.games(id, name, "number") VALUES (3,'7wonders',2);
INSERT INTO guild.games(id, name, "number") VALUES (4,'7wonders architects',1);
INSERT INTO guild.games(id, name, "number") VALUES (5,'7wonders babel',1);
INSERT INTO guild.games(id, name, "number") VALUES (6,'7wonders cities',1);
INSERT INTO guild.games(id, name, "number") VALUES (7,'7wonders duel',2);
INSERT INTO guild.games(id, name, "number") VALUES (8,'7wonders leaders',1);
INSERT INTO guild.games(id, name, "number") VALUES (9,'7wonders wonderpack',1);
INSERT INTO guild.games(id, name, "number") VALUES (10,'878 – vikings',1);
INSERT INTO guild.games(id, name, "number") VALUES (11,'abalone',1);
INSERT INTO guild.games(id, name, "number") VALUES (12,'agricola',1);
INSERT INTO guild.games(id, name, "number") VALUES (13,'airlines',1);
INSERT INTO guild.games(id, name, "number") VALUES (14,'alchimisti',1);
INSERT INTO guild.games(id, name, "number") VALUES (15,'alta tensione espansione australia /india subcontinelate (tedesco)',1);
INSERT INTO guild.games(id, name, "number") VALUES (16,'alta tensione espansione benelux / europa centrale',1);
INSERT INTO guild.games(id, name, "number") VALUES (17,'alta tensione fabrik manager',1);
INSERT INTO guild.games(id, name, "number") VALUES (18,'alta tensione il gioco delle centrali elettriche',1);
INSERT INTO guild.games(id, name, "number") VALUES (19,'amul',1);
INSERT INTO guild.games(id, name, "number") VALUES (20,'aquatica',1);
INSERT INTO guild.games(id, name, "number") VALUES (21,'architetti del regno occidentale',1);
INSERT INTO guild.games(id, name, "number") VALUES (22,'aristeia!',1);
INSERT INTO guild.games(id, name, "number") VALUES (23,'arkham horror',1);
INSERT INTO guild.games(id, name, "number") VALUES (24,'arrogh-tek',1);
INSERT INTO guild.games(id, name, "number") VALUES (25,'assist',1);
INSERT INTO guild.games(id, name, "number") VALUES (26,'atlantis',1);
INSERT INTO guild.games(id, name, "number") VALUES (27,'ave ceaser',1);
INSERT INTO guild.games(id, name, "number") VALUES (28,'axis & allies europe',1);
INSERT INTO guild.games(id, name, "number") VALUES (29,'axis & allies spring 1942',1);
INSERT INTO guild.games(id, name, "number") VALUES (30,'azul',1);
INSERT INTO guild.games(id, name, "number") VALUES (31,'azul le vetrate di sintra',1);
INSERT INTO guild.games(id, name, "number") VALUES (32,'bang!',1);
INSERT INTO guild.games(id, name, "number") VALUES (33,'bang! samurai sword',1);
INSERT INTO guild.games(id, name, "number") VALUES (34,'battlestar galactica',1);
INSERT INTO guild.games(id, name, "number") VALUES (35,'beez',1);
INSERT INTO guild.games(id, name, "number") VALUES (36,'bicchieri sprint',1);
INSERT INTO guild.games(id, name, "number") VALUES (37,'blackout hong kong',1);
INSERT INTO guild.games(id, name, "number") VALUES (38,'blue max',1);
INSERT INTO guild.games(id, name, "number") VALUES (39,'bohnanza',1);
INSERT INTO guild.games(id, name, "number") VALUES (40,'bookmaker',1);
INSERT INTO guild.games(id, name, "number") VALUES (41,'bora bora',1);
INSERT INTO guild.games(id, name, "number") VALUES (42,'brew',1);
INSERT INTO guild.games(id, name, "number") VALUES (43,'britannia',1);
INSERT INTO guild.games(id, name, "number") VALUES (44,'c’era una volta',1);
INSERT INTO guild.games(id, name, "number") VALUES (45,'caercassonne',1);
INSERT INTO guild.games(id, name, "number") VALUES (46,'caercassonne abbazzie e borgomastri',1);
INSERT INTO guild.games(id, name, "number") VALUES (47,'caercassonne il conte, il re e l’eretico',1);
INSERT INTO guild.games(id, name, "number") VALUES (48,'callisto',1);
INSERT INTO guild.games(id, name, "number") VALUES (49,'camel up',1);
INSERT INTO guild.games(id, name, "number") VALUES (50,'cartagena',1);
INSERT INTO guild.games(id, name, "number") VALUES (51,'catalyst',1);
INSERT INTO guild.games(id, name, "number") VALUES (52,'caylus',1);
INSERT INTO guild.games(id, name, "number") VALUES (53,'century la via delle spezie',1);
INSERT INTO guild.games(id, name, "number") VALUES (54,'century meraviglie orientali',1);
INSERT INTO guild.games(id, name, "number") VALUES (55,'chaos in the old world',1);
INSERT INTO guild.games(id, name, "number") VALUES (56,'chaterstone',1);
INSERT INTO guild.games(id, name, "number") VALUES (57,'chez geek bisboccia edition',1);
INSERT INTO guild.games(id, name, "number") VALUES (58,'cin cin',1);
INSERT INTO guild.games(id, name, "number") VALUES (59,'citadels',1);
INSERT INTO guild.games(id, name, "number") VALUES (60,'claim 2',1);
INSERT INTO guild.games(id, name, "number") VALUES (61,'colt express',1);
INSERT INTO guild.games(id, name, "number") VALUES (62,'concordia',1);
INSERT INTO guild.games(id, name, "number") VALUES (63,'connect 5',1);
INSERT INTO guild.games(id, name, "number") VALUES (64,'conquest of paradise',1);
INSERT INTO guild.games(id, name, "number") VALUES (65,'corsari dei caraibi',1);
INSERT INTO guild.games(id, name, "number") VALUES (66,'corsari dei caraibi mari della gloria',1);
INSERT INTO guild.games(id, name, "number") VALUES (67,'cottage garden',1);
INSERT INTO guild.games(id, name, "number") VALUES (68,'creature comforts',1);
INSERT INTO guild.games(id, name, "number") VALUES (69,'cyberdoom tower',1);
INSERT INTO guild.games(id, name, "number") VALUES (70,'cyclades',1);
INSERT INTO guild.games(id, name, "number") VALUES (71,'cyclades hades',1);
INSERT INTO guild.games(id, name, "number") VALUES (72,'cyclades titans',1);
INSERT INTO guild.games(id, name, "number") VALUES (73,'deadline la sopravvivenza ha inizio',1);
INSERT INTO guild.games(id, name, "number") VALUES (74,'descent: viaggi nelle tenebre',1);
INSERT INTO guild.games(id, name, "number") VALUES (75,'detective sulla scena del crimine',1);
INSERT INTO guild.games(id, name, "number") VALUES (76,'dice run',1);
INSERT INTO guild.games(id, name, "number") VALUES (77,'dice town',1);
INSERT INTO guild.games(id, name, "number") VALUES (78,'diplomacy',1);
INSERT INTO guild.games(id, name, "number") VALUES (79,'diplomacy anniversary',1);
INSERT INTO guild.games(id, name, "number") VALUES (80,'dispettrice!',1);
INSERT INTO guild.games(id, name, "number") VALUES (81,'dixit daydrams',1);
INSERT INTO guild.games(id, name, "number") VALUES (82,'dominion',1);
INSERT INTO guild.games(id, name, "number") VALUES (83,'dominion alchimia',1);
INSERT INTO guild.games(id, name, "number") VALUES (84,'dominion avventure',1);
INSERT INTO guild.games(id, name, "number") VALUES (85,'dominion cornucopia',1);
INSERT INTO guild.games(id, name, "number") VALUES (86,'dominion intrigo',1);
INSERT INTO guild.games(id, name, "number") VALUES (87,'dominion nuovi orizzonti',1);
INSERT INTO guild.games(id, name, "number") VALUES (88,'dominion prosperità',1);
INSERT INTO guild.games(id, name, "number") VALUES (89,'don quixote',1);
INSERT INTO guild.games(id, name, "number") VALUES (90,'draftosaurus',1);
INSERT INTO guild.games(id, name, "number") VALUES (91,'drizzit draghi, spose e coccole estreme – espansione 1',1);
INSERT INTO guild.games(id, name, "number") VALUES (92,'drizzit il gioco di carte',1);
INSERT INTO guild.games(id, name, "number") VALUES (93,'dune',1);
INSERT INTO guild.games(id, name, "number") VALUES (94,'dungeon fighter',1);
INSERT INTO guild.games(id, name, "number") VALUES (95,'dungeon hoeros manager',1);
INSERT INTO guild.games(id, name, "number") VALUES (96,'dungeon lords',1);
INSERT INTO guild.games(id, name, "number") VALUES (97,'dungeon venture gioco da tavolo fantasy',1);
INSERT INTO guild.games(id, name, "number") VALUES (98,'dungeonquest',1);
INSERT INTO guild.games(id, name, "number") VALUES (99,'el grande',1);
INSERT INTO guild.games(id, name, "number") VALUES (100,'eldritch horror',1);
INSERT INTO guild.games(id, name, "number") VALUES (101,'elfenland de lux',1);
INSERT INTO guild.games(id, name, "number") VALUES (102,'emira',1);
INSERT INTO guild.games(id, name, "number") VALUES (103,'endevor',1);
INSERT INTO guild.games(id, name, "number") VALUES (104,'exploding kittens',1);
INSERT INTO guild.games(id, name, "number") VALUES (105,'exscape',1);
INSERT INTO guild.games(id, name, "number") VALUES (106,'fabula',1);
INSERT INTO guild.games(id, name, "number") VALUES (107,'fairy tale',1);
INSERT INTO guild.games(id, name, "number") VALUES (108,'fantascatti',1);
INSERT INTO guild.games(id, name, "number") VALUES (109,'fantascatti 2',1);
INSERT INTO guild.games(id, name, "number") VALUES (110,'fantasy pub',1);
INSERT INTO guild.games(id, name, "number") VALUES (111,'fire & axe – a viking saga',1);
INSERT INTO guild.games(id, name, "number") VALUES (112,'flamme rouge',1);
INSERT INTO guild.games(id, name, "number") VALUES (113,'formula d',1);
INSERT INTO guild.games(id, name, "number") VALUES (114,'formula d – espansione 2: hockenheimring / valencia',1);
INSERT INTO guild.games(id, name, "number") VALUES (115,'formula de',1);
INSERT INTO guild.games(id, name, "number") VALUES (116,'fort',1);
INSERT INTO guild.games(id, name, "number") VALUES (117,'fortress america',1);
INSERT INTO guild.games(id, name, "number") VALUES (118,'fun farm',1);
INSERT INTO guild.games(id, name, "number") VALUES (119,'galactic emperor',1);
INSERT INTO guild.games(id, name, "number") VALUES (120,'galaxy trucker',1);
INSERT INTO guild.games(id, name, "number") VALUES (121,'gli allegri pirati',1);
INSERT INTO guild.games(id, name, "number") VALUES (122,'gli avventurieri il tempio di chac',1);
INSERT INTO guild.games(id, name, "number") VALUES (123,'goa',1);
INSERT INTO guild.games(id, name, "number") VALUES (124,'godz',1);
INSERT INTO guild.games(id, name, "number") VALUES (125,'halli galli',1);
INSERT INTO guild.games(id, name, "number") VALUES (126,'hanabi',1);
INSERT INTO guild.games(id, name, "number") VALUES (127,'hats',1);
INSERT INTO guild.games(id, name, "number") VALUES (128,'hexemoniaù',1);
INSERT INTO guild.games(id, name, "number") VALUES (129,'hidden leadres',1);
INSERT INTO guild.games(id, name, "number") VALUES (130,'hidden war',1);
INSERT INTO guild.games(id, name, "number") VALUES (131,'hobbit tales',1);
INSERT INTO guild.games(id, name, "number") VALUES (132,'horns up',1);
INSERT INTO guild.games(id, name, "number") VALUES (133,'horse fever',1);
INSERT INTO guild.games(id, name, "number") VALUES (134,'hyperborea',1);
INSERT INTO guild.games(id, name, "number") VALUES (135,'i castelli della borgogna',1);
INSERT INTO guild.games(id, name, "number") VALUES (136,'i coloni di catan',1);
INSERT INTO guild.games(id, name, "number") VALUES (137,'i coloni di catan – battaglia per roma',1);
INSERT INTO guild.games(id, name, "number") VALUES (138,'i coloni di catan – europa medievale',1);
INSERT INTO guild.games(id, name, "number") VALUES (139,'i coloni di catan – gioco di carte',1);
INSERT INTO guild.games(id, name, "number") VALUES (140,'i coloni di catan – gioco di dadi',1);
INSERT INTO guild.games(id, name, "number") VALUES (141,'i coloni di catan – marinai (espansione)',1);
INSERT INTO guild.games(id, name, "number") VALUES (142,'i ladri di bagdad',1);
INSERT INTO guild.games(id, name, "number") VALUES (143,'i tiranni dell’underdark il gioco da tavolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (144,'il castello',1);
INSERT INTO guild.games(id, name, "number") VALUES (145,'il castello del diavolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (146,'il grande dalmuti',1);
INSERT INTO guild.games(id, name, "number") VALUES (147,'il re dei nani',1);
INSERT INTO guild.games(id, name, "number") VALUES (148,'il segno degli antichi',1);
INSERT INTO guild.games(id, name, "number") VALUES (149,'il trono di spade',1);
INSERT INTO guild.games(id, name, "number") VALUES (150,'indian summer',1);
INSERT INTO guild.games(id, name, "number") VALUES (151,'innovation',1);
INSERT INTO guild.games(id, name, "number") VALUES (152,'insert coin to play',1);
INSERT INTO guild.games(id, name, "number") VALUES (153,'insoliti sospetti',1);
INSERT INTO guild.games(id, name, "number") VALUES (154,'italia',1);
INSERT INTO guild.games(id, name, "number") VALUES (155,'jenga',1);
INSERT INTO guild.games(id, name, "number") VALUES (156,'jenga boom',1);
INSERT INTO guild.games(id, name, "number") VALUES (157,'jenus il gioco',1);
INSERT INTO guild.games(id, name, "number") VALUES (158,'jerusalem',1);
INSERT INTO guild.games(id, name, "number") VALUES (159,'joomba!',1);
INSERT INTO guild.games(id, name, "number") VALUES (160,'jungle speed',1);
INSERT INTO guild.games(id, name, "number") VALUES (161,'jungle speed l’espansione',1);
INSERT INTO guild.games(id, name, "number") VALUES (162,'jungle speed safari',1);
INSERT INTO guild.games(id, name, "number") VALUES (163,'kaleidos',1);
INSERT INTO guild.games(id, name, "number") VALUES (164,'kemet',1);
INSERT INTO guild.games(id, name, "number") VALUES (165,'kharnage hell yearghh!',1);
INSERT INTO guild.games(id, name, "number") VALUES (166,'kill doctor lucky',1);
INSERT INTO guild.games(id, name, "number") VALUES (167,'king fu zoo',1);
INSERT INTO guild.games(id, name, "number") VALUES (168,'king of tokyo',1);
INSERT INTO guild.games(id, name, "number") VALUES (169,'king of tokyo expansion 1',1);
INSERT INTO guild.games(id, name, "number") VALUES (170,'kingdomino',2);
INSERT INTO guild.games(id, name, "number") VALUES (171,'kingsburg',1);
INSERT INTO guild.games(id, name, "number") VALUES (172,'kingsburg – l’espansione del regno',1);
INSERT INTO guild.games(id, name, "number") VALUES (173,'kingsport festival',1);
INSERT INTO guild.games(id, name, "number") VALUES (174,'kragmortha',1);
INSERT INTO guild.games(id, name, "number") VALUES (175,'kung fu',1);
INSERT INTO guild.games(id, name, "number") VALUES (176,'l’isola proibita',1);
INSERT INTO guild.games(id, name, "number") VALUES (177,'la boca',1);
INSERT INTO guild.games(id, name, "number") VALUES (178,'la furia di dracula',1);
INSERT INTO guild.games(id, name, "number") VALUES (179,'la guerra dell’anello',1);
INSERT INTO guild.games(id, name, "number") VALUES (180,'lascaux',1);
INSERT INTO guild.games(id, name, "number") VALUES (181,'le battaglie di westeros',1);
INSERT INTO guild.games(id, name, "number") VALUES (182,'le case della follia',1);
INSERT INTO guild.games(id, name, "number") VALUES (183,'le havre',1);
INSERT INTO guild.games(id, name, "number") VALUES (184,'le havre ancora in porto',1);
INSERT INTO guild.games(id, name, "number") VALUES (185,'le leggende di andor',1);
INSERT INTO guild.games(id, name, "number") VALUES (186,'le strade d’inchiostro',1);
INSERT INTO guild.games(id, name, "number") VALUES (187,'lettera da whitechapel',1);
INSERT INTO guild.games(id, name, "number") VALUES (188,'libertalia',1);
INSERT INTO guild.games(id, name, "number") VALUES (189,'loch ness',1);
INSERT INTO guild.games(id, name, "number") VALUES (190,'lugarno',1);
INSERT INTO guild.games(id, name, "number") VALUES (191,'lupus in tabula',1);
INSERT INTO guild.games(id, name, "number") VALUES (192,'madame ching',1);
INSERT INTO guild.games(id, name, "number") VALUES (193,'madeira',1);
INSERT INTO guild.games(id, name, "number") VALUES (194,'maestri del rinascimento',1);
INSERT INTO guild.games(id, name, "number") VALUES (195,'magic maze kids',1);
INSERT INTO guild.games(id, name, "number") VALUES (196,'maiali al galoppo',1);
INSERT INTO guild.games(id, name, "number") VALUES (197,'majesty',1);
INSERT INTO guild.games(id, name, "number") VALUES (198,'mall of horror',1);
INSERT INTO guild.games(id, name, "number") VALUES (199,'mamma mia!',1);
INSERT INTO guild.games(id, name, "number") VALUES (200,'manifest destiny',1);
INSERT INTO guild.games(id, name, "number") VALUES (201,'manila',1);
INSERT INTO guild.games(id, name, "number") VALUES (202,'maracaibo',1);
INSERT INTO guild.games(id, name, "number") VALUES (203,'mare nostrum imperi',1);
INSERT INTO guild.games(id, name, "number") VALUES (204,'marvel x-men mutant insurrection',1);
INSERT INTO guild.games(id, name, "number") VALUES (205,'mascarade',1);
INSERT INTO guild.games(id, name, "number") VALUES (206,'mass up',1);
INSERT INTO guild.games(id, name, "number") VALUES (207,'mate knight',1);
INSERT INTO guild.games(id, name, "number") VALUES (208,'memory',1);
INSERT INTO guild.games(id, name, "number") VALUES (209,'meridian',1);
INSERT INTO guild.games(id, name, "number") VALUES (210,'mice & mystics',1);
INSERT INTO guild.games(id, name, "number") VALUES (211,'micro macro crime city',1);
INSERT INTO guild.games(id, name, "number") VALUES (212,'micro mutants evolution',1);
INSERT INTO guild.games(id, name, "number") VALUES (213,'micromondo',1);
INSERT INTO guild.games(id, name, "number") VALUES (214,'midgard',1);
INSERT INTO guild.games(id, name, "number") VALUES (215,'misantropia express',1);
INSERT INTO guild.games(id, name, "number") VALUES (216,'mondo',1);
INSERT INTO guild.games(id, name, "number") VALUES (217,'mondo senza fine',1);
INSERT INTO guild.games(id, name, "number") VALUES (218,'monster slaughter',1);
INSERT INTO guild.games(id, name, "number") VALUES (219,'mozaika',1);
INSERT INTO guild.games(id, name, "number") VALUES (220,'mr. jack',1);
INSERT INTO guild.games(id, name, "number") VALUES (221,'munchkin',1);
INSERT INTO guild.games(id, name, "number") VALUES (222,'munchkin dei caraibi',1);
INSERT INTO guild.games(id, name, "number") VALUES (223,'munchkin dungeon',1);
INSERT INTO guild.games(id, name, "number") VALUES (224,'munchkin memo',1);
INSERT INTO guild.games(id, name, "number") VALUES (225,'munchkin morde! di nuovo',1);
INSERT INTO guild.games(id, name, "number") VALUES (226,'munchkin star',1);
INSERT INTO guild.games(id, name, "number") VALUES (227,'mythos',1);
INSERT INTO guild.games(id, name, "number") VALUES (228,'newton',1);
INSERT INTO guild.games(id, name, "number") VALUES (229,'niagara',1);
INSERT INTO guild.games(id, name, "number") VALUES (230,'nippon',1);
INSERT INTO guild.games(id, name, "number") VALUES (231,'non t’arrabbi are il gioco del buonumore',1);
INSERT INTO guild.games(id, name, "number") VALUES (232,'notte dame',1);
INSERT INTO guild.games(id, name, "number") VALUES (233,'novembre rosso',1);
INSERT INTO guild.games(id, name, "number") VALUES (234,'ok ko l’era di asagiri',1);
INSERT INTO guild.games(id, name, "number") VALUES (235,'omega il gioco',1);
INSERT INTO guild.games(id, name, "number") VALUES (236,'one card dungeon',1);
INSERT INTO guild.games(id, name, "number") VALUES (237,'one desk dungeon la foresta delle ombre',1);
INSERT INTO guild.games(id, name, "number") VALUES (238,'orifiamma ablaze',1);
INSERT INTO guild.games(id, name, "number") VALUES (239,'pandemia',1);
INSERT INTO guild.games(id, name, "number") VALUES (240,'panic lab',1);
INSERT INTO guild.games(id, name, "number") VALUES (241,'pathfinder adventure card game ascesa dei signori delle rune',1);
INSERT INTO guild.games(id, name, "number") VALUES (242,'pecore al pascolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (243,'perudo',1);
INSERT INTO guild.games(id, name, "number") VALUES (244,'phantom society grand palace hotel',1);
INSERT INTO guild.games(id, name, "number") VALUES (245,'picchiatello',1);
INSERT INTO guild.games(id, name, "number") VALUES (246,'pilastri della terra',1);
INSERT INTO guild.games(id, name, "number") VALUES (247,'pinguin pescatore',1);
INSERT INTO guild.games(id, name, "number") VALUES (248,'pinnacolando',1);
INSERT INTO guild.games(id, name, "number") VALUES (249,'plagio',1);
INSERT INTO guild.games(id, name, "number") VALUES (250,'poker madness',1);
INSERT INTO guild.games(id, name, "number") VALUES (251,'pozioni esplosive',1);
INSERT INTO guild.games(id, name, "number") VALUES (252,'puerto rico',1);
INSERT INTO guild.games(id, name, "number") VALUES (253,'quarantine',1);
INSERT INTO guild.games(id, name, "number") VALUES (254,'quarriors!',1);
INSERT INTO guild.games(id, name, "number") VALUES (255,'quetzal',1);
INSERT INTO guild.games(id, name, "number") VALUES (256,'railroad revolution',1);
INSERT INTO guild.games(id, name, "number") VALUES (257,'richard i',1);
INSERT INTO guild.games(id, name, "number") VALUES (258,'riders of the north sea',1);
INSERT INTO guild.games(id, name, "number") VALUES (259,'risiko!',1);
INSERT INTO guild.games(id, name, "number") VALUES (260,'risiko! (1997)',1);
INSERT INTO guild.games(id, name, "number") VALUES (261,'risiko! futurisiko!',1);
INSERT INTO guild.games(id, name, "number") VALUES (262,'risiko! portatile',1);
INSERT INTO guild.games(id, name, "number") VALUES (263,'risiko! s.p.q.r',1);
INSERT INTO guild.games(id, name, "number") VALUES (264,'risiko! sturmtruppen',1);
INSERT INTO guild.games(id, name, "number") VALUES (265,'rising sun',1);
INSERT INTO guild.games(id, name, "number") VALUES (266,'robo troc',1);
INSERT INTO guild.games(id, name, "number") VALUES (267,'rock’n’roll robot',1);
INSERT INTO guild.games(id, name, "number") VALUES (268,'room-25',1);
INSERT INTO guild.games(id, name, "number") VALUES (269,'rune age',1);
INSERT INTO guild.games(id, name, "number") VALUES (270,'rune wards',1);
INSERT INTO guild.games(id, name, "number") VALUES (271,'rush & bash',1);
INSERT INTO guild.games(id, name, "number") VALUES (272,'rush n’ crush the armed racing game!',1);
INSERT INTO guild.games(id, name, "number") VALUES (273,'saboteur',1);
INSERT INTO guild.games(id, name, "number") VALUES (274,'sagrada',1);
INSERT INTO guild.games(id, name, "number") VALUES (275,'santorini',1);
INSERT INTO guild.games(id, name, "number") VALUES (276,'scarabeo flash',1);
INSERT INTO guild.games(id, name, "number") VALUES (277,'scythe',1);
INSERT INTO guild.games(id, name, "number") VALUES (278,'seasons',1);
INSERT INTO guild.games(id, name, "number") VALUES (279,'seasons enchanted kingodom',1);
INSERT INTO guild.games(id, name, "number") VALUES (280,'seasons path of destiny',1);
INSERT INTO guild.games(id, name, "number") VALUES (281,'sei … prendi e perdi!',1);
INSERT INTO guild.games(id, name, "number") VALUES (282,'semenza',1);
INSERT INTO guild.games(id, name, "number") VALUES (283,'senji',1);
INSERT INTO guild.games(id, name, "number") VALUES (284,'serenissima',1);
INSERT INTO guild.games(id, name, "number") VALUES (285,'shadows over the empire',1);
INSERT INTO guild.games(id, name, "number") VALUES (286,'sheepland',1);
INSERT INTO guild.games(id, name, "number") VALUES (287,'sherlock holmes consulente investigativo',1);
INSERT INTO guild.games(id, name, "number") VALUES (288,'shifting stones',1);
INSERT INTO guild.games(id, name, "number") VALUES (289,'sì, oscuro padrino!',1);
INSERT INTO guild.games(id, name, "number") VALUES (290,'sì, oscuro signore!',1);
INSERT INTO guild.games(id, name, "number") VALUES (291,'sì, oscuro signore! set base verde',1);
INSERT INTO guild.games(id, name, "number") VALUES (292,'skytear',1);
INSERT INTO guild.games(id, name, "number") VALUES (293,'small star empires',1);
INSERT INTO guild.games(id, name, "number") VALUES (294,'smallworld',1);
INSERT INTO guild.games(id, name, "number") VALUES (295,'smallworld underground',1);
INSERT INTO guild.games(id, name, "number") VALUES (296,'soqquadro',1);
INSERT INTO guild.games(id, name, "number") VALUES (297,'space alert',1);
INSERT INTO guild.games(id, name, "number") VALUES (298,'space alert the new frontier',1);
INSERT INTO guild.games(id, name, "number") VALUES (299,'splendor',2);
INSERT INTO guild.games(id, name, "number") VALUES (300,'star realms gioco di carte',1);
INSERT INTO guild.games(id, name, "number") VALUES (301,'star wars assalto imperiale',1);
INSERT INTO guild.games(id, name, "number") VALUES (302,'starcraft : il gioco da tavolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (303,'stay away',1);
INSERT INTO guild.games(id, name, "number") VALUES (304,'steampark',1);
INSERT INTO guild.games(id, name, "number") VALUES (305,'steel driver',1);
INSERT INTO guild.games(id, name, "number") VALUES (306,'stone age alla metà con stile',1);
INSERT INTO guild.games(id, name, "number") VALUES (307,'stone age l’inizio del viaggio',1);
INSERT INTO guild.games(id, name, "number") VALUES (308,'storie gialle 50 misteri da risolvere',1);
INSERT INTO guild.games(id, name, "number") VALUES (309,'sulle tracce di marco polo',1);
INSERT INTO guild.games(id, name, "number") VALUES (310,'super fantasy la notte dei morti male',1);
INSERT INTO guild.games(id, name, "number") VALUES (311,'super farmer',1);
INSERT INTO guild.games(id, name, "number") VALUES (312,'sushi go!',1);
INSERT INTO guild.games(id, name, "number") VALUES (313,'swordcrafters',1);
INSERT INTO guild.games(id, name, "number") VALUES (314,'swordfish',1);
INSERT INTO guild.games(id, name, "number") VALUES (315,'taboo',1);
INSERT INTO guild.games(id, name, "number") VALUES (316,'takenoko',1);
INSERT INTO guild.games(id, name, "number") VALUES (317,'talisman',1);
INSERT INTO guild.games(id, name, "number") VALUES (318,'tannhauser',1);
INSERT INTO guild.games(id, name, "number") VALUES (319,'tea time',1);
INSERT INTO guild.games(id, name, "number") VALUES (320,'team menager blood bowl',1);
INSERT INTO guild.games(id, name, "number") VALUES (321,'terraforming mars',1);
INSERT INTO guild.games(id, name, "number") VALUES (322,'tesseract',1);
INSERT INTO guild.games(id, name, "number") VALUES (323,'the boss',1);
INSERT INTO guild.games(id, name, "number") VALUES (324,'the island',1);
INSERT INTO guild.games(id, name, "number") VALUES (325,'the king is dead',1);
INSERT INTO guild.games(id, name, "number") VALUES (326,'the red cathedral',1);
INSERT INTO guild.games(id, name, "number") VALUES (327,'thematik prendi al volo la parola',1);
INSERT INTO guild.games(id, name, "number") VALUES (328,'tichu',1);
INSERT INTO guild.games(id, name, "number") VALUES (329,'ticket to ride',1);
INSERT INTO guild.games(id, name, "number") VALUES (330,'ticket to ride asia',1);
INSERT INTO guild.games(id, name, "number") VALUES (331,'ticket to ride europe',1);
INSERT INTO guild.games(id, name, "number") VALUES (332,'ticket to ride france',1);
INSERT INTO guild.games(id, name, "number") VALUES (333,'ticket to ride india',1);
INSERT INTO guild.games(id, name, "number") VALUES (334,'ticket to ride nederland',1);
INSERT INTO guild.games(id, name, "number") VALUES (335,'ticket to ride primo viaggio',1);
INSERT INTO guild.games(id, name, "number") VALUES (336,'ticket to ride the heart of africa',1);
INSERT INTO guild.games(id, name, "number") VALUES (337,'ticket to ride united kingdom',1);
INSERT INTO guild.games(id, name, "number") VALUES (338,'ticket to ride usa 1910',1);
INSERT INTO guild.games(id, name, "number") VALUES (339,'tigri & eufrate',1);
INSERT INTO guild.games(id, name, "number") VALUES (340,'tikal ii',1);
INSERT INTO guild.games(id, name, "number") VALUES (341,'time’s up!',1);
INSERT INTO guild.games(id, name, "number") VALUES (342,'time’s up! celebrity 1',1);
INSERT INTO guild.games(id, name, "number") VALUES (343,'tobago',1);
INSERT INTO guild.games(id, name, "number") VALUES (344,'toledo',1);
INSERT INTO guild.games(id, name, "number") VALUES (345,'trajan',1);
INSERT INTO guild.games(id, name, "number") VALUES (346,'tutankhamun',1);
INSERT INTO guild.games(id, name, "number") VALUES (347,'tweegles',1);
INSERT INTO guild.games(id, name, "number") VALUES (348,'twilight struggle la guerra fredda, 1945-1989',1);
INSERT INTO guild.games(id, name, "number") VALUES (349,'tzolk’in il calendario maya',1);
INSERT INTO guild.games(id, name, "number") VALUES (350,'tzolk’in tribù e profezie',1);
INSERT INTO guild.games(id, name, "number") VALUES (351,'utopia',1);
INSERT INTO guild.games(id, name, "number") VALUES (352,'vampiri: vendetta',1);
INSERT INTO guild.games(id, name, "number") VALUES (353,'vasco da gama',1);
INSERT INTO guild.games(id, name, "number") VALUES (354,'vektorace',1);
INSERT INTO guild.games(id, name, "number") VALUES (355,'ventura',1);
INSERT INTO guild.games(id, name, "number") VALUES (356,'versailles',1);
INSERT INTO guild.games(id, name, "number") VALUES (357,'vi du’',1);
INSERT INTO guild.games(id, name, "number") VALUES (358,'villa paletti',1);
INSERT INTO guild.games(id, name, "number") VALUES (359,'village',1);
INSERT INTO guild.games(id, name, "number") VALUES (360,'viticulture',1);
INSERT INTO guild.games(id, name, "number") VALUES (361,'warhammer 40.000 heroes of black reach',1);
INSERT INTO guild.games(id, name, "number") VALUES (362,'warhammer 40.000 relic',1);
INSERT INTO guild.games(id, name, "number") VALUES (363,'warhammer invasion il gioco di carte',1);
INSERT INTO guild.games(id, name, "number") VALUES (364,'warhammer invasion il gioco di carte cataclysm expansion',1);
INSERT INTO guild.games(id, name, "number") VALUES (365,'warlords of europe',1);
INSERT INTO guild.games(id, name, "number") VALUES (366,'welcome too',1);
INSERT INTO guild.games(id, name, "number") VALUES (367,'werner i dream',1);
INSERT INTO guild.games(id, name, "number") VALUES (368,'what’s he building in there?',1);
INSERT INTO guild.games(id, name, "number") VALUES (369,'whitehall mistery',1);
INSERT INTO guild.games(id, name, "number") VALUES (370,'wings of war',1);
INSERT INTO guild.games(id, name, "number") VALUES (371,'wings of war miniatures deluxe set',1);
INSERT INTO guild.games(id, name, "number") VALUES (372,'world of warcraft : il gioco da tavolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (373,'world of warcraft whaath of the lich king',1);
INSERT INTO guild.games(id, name, "number") VALUES (374,'xcom il gioco da tavolo',1);
INSERT INTO guild.games(id, name, "number") VALUES (375,'xi’an',1);
INSERT INTO guild.games(id, name, "number") VALUES (376,'yahtzee!',1);
INSERT INTO guild.games(id, name, "number") VALUES (377,'yoko hama',1);
INSERT INTO guild.games(id, name, "number") VALUES (378,'zombi!!!',1);
INSERT INTO guild.games(id, name, "number") VALUES (379,'zombicide',1);
INSERT INTO guild.games(id, name, "number") VALUES (380,'zombie dice',1);
INSERT INTO guild.games(id, name, "number") VALUES (381,'zooloretto',1);